add new post cohort-1-ana
PlatziMaster/platzimaster-deprecated pull request #30
Opened 2020-04-03 20:59 UTC by jeff-js

## DESCRIPTION

Add new post to team leader tips

## INFORMATION

```yaml
name: Cohort 1 Ana
username: https://platzi.com/
coach: Ana
cohort: 1
```

## PR TYPE

- [X] BlogPost
- [ ] BugFix
- [ ] Feature
- [ ] Enhancement

2020-04-03 23:24 UTC, gndx requested changes

2020-04-03 23:24 UTC, gndx commented on content/2020/0403-liderazgo-de-equipos.md
> +
Eliminar estos espacios

2020-04-03 23:26 UTC, gndx requested changes

2020-04-03 23:26 UTC, gndx commented on content/2020/0403-liderazgo-de-equipos.md
> +platziUser: '@cohort1-team-ana'
Este no es tu Platzi User.

2020-04-04 00:27 UTC, jeff-js commented on content/2020/0403-liderazgo-de-equipos.md
> +platziUser: '@cohort1-team-ana'
Hola @gndx ya fue corregido el usuario

2020-04-04 00:28 UTC, jeff-js commented on content/2020/0403-liderazgo-de-equipos.md
> +
se ha eliminado estos

2020-04-06 03:38 UTC, gndx requested changes

2020-04-06 03:38 UTC, gndx commented on content/2020/0403-liderazgo-de-equipos.md
> +platziUser: '@jeff-js'
Sin @

2020-04-06 03:38 UTC, gndx commented on README.md
> +[![Build Status](https://travis-ci.org/PlatziMaster/platzimaster.github.io.svg?branch=develop)](https://travis-ci.org/PlatziMaster/platzimaster.github.io)
Envia este cambio en otro PR para separar tu blogpost de un Feature.

2020-04-06 03:38 UTC, gndx commented on content/2020/0403-liderazgo-de-equipos.md
> +![Lider-Jefe](https://www.ucsc.cl/wp-content/uploads/2019/08/lider-vs-jefe.jpg)
Usar imagenes propias, subirlas a drive o utiliza https://giphy.com/

2020-04-06 04:46 UTC, jeff-js commented on content/2020/0403-liderazgo-de-equipos.md
> +platziUser: '@jeff-js'
Hola @gndx solucionado esto

2020-04-06 04:46 UTC, jeff-js commented on README.md
> +[![Build Status](https://travis-ci.org/PlatziMaster/platzimaster.github.io.svg?branch=develop)](https://travis-ci.org/PlatziMaster/platzimaster.github.io)
Hola @gndx se ha removido esto

2020-04-06 04:47 UTC, jeff-js commented on content/2020/0403-liderazgo-de-equipos.md
> +![Lider-Jefe](https://www.ucsc.cl/wp-content/uploads/2019/08/lider-vs-jefe.jpg)
Hola @gndx la he quitado, no se mostraba al dejarla en mi drive :(

2020-04-06 15:51 UTC, gndx approved these changes

2020-04-09 18:52 UTC, gndx approved these changes

2020-04-09 18:52 UTC, merged